language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
before_deploy: "npm run build"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $PROJECT_NAME
  skip_cleanup: true﻿
