{
        language: node_js
        node_js:
        - "8"
        - "6"
        deploy:
          provider: firebase
          skip_cleanup: true
          travis encrypt "1/xSsTgBavcIv-_axuUOLQU8fdw2eoq1Fkrc_laR4KKlU" --add deploy.token
